server:
  port: 9092
spring:
  application:
    name: redis-feign-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

feign:
  client:
    config:
      # 服务名，default表示为所有服务
      default:
        # 即便feign使用OkHttp，但是寻常配置OkHttp的方式来配置超时时间是不生效的，只能这样配置
        # 连接超时时间，单位为 ms
        connectTimeout: 10000
        # 读取超时时间，单位为 ms
        readTimeout: 25000
  hystrix:
    enabled: false
  compression:
    request:
      # 是否对请求进行GZIP压缩
      enabled: false
      # 指定压缩的请求数据类型
      mime-types: text/xml,application/xml,application/json
      # 超过该大小的请求会被压缩
      min-request-size: 2048
    response:
      # 是否对响应进行GZIP压缩
      enabled: false
  okhttp:
    enabled: true
  httpclient:
    enabled: false


hystrix:
  threadpool:
    default:
      #并发执行的最大线程数
      coreSize: 200
      #BlockingQueue的最大队列数，默认值-1
      maxQueueSize: 1000
      #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝，默认值5
      queueSizeRejectionThreshold: 800
