eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

spring:
  application:
    name: gateway-service
#  cloud:
#    gateway:
#      routes:
#          # 路由的id，服务名
#        - id: redis-lock-client
#          # lb代表从注册中心获取服务，并且以负载均衡方式转发
#          uri: lb://redis-lock-client
#          predicates:
#            # 这里的Path配置的是对应服务的前缀，依靠前缀分发到不同的服务上
#            - Path=/client/**
#            # 这里的Header配置的是对应服务的header断言，需要有一个header参数名是tenant的值是test
#            - Header=tenant,test
#          # 加上StripPrefix=1，否则转发到对应服务时会带上前缀
#          filters:
#            - StripPrefix=1
  redis:
    # redis服务端口号
    port: 6379
    # redis服务地址
    host: 127.0.0.1
    # lettuce连接池配置
    lettuce:
      pool:
        # 连接池最大阻塞等待时间
        max-wait: 1000ms
        # 最大空闲数
        max-idle: 8
        # 最小空闲数
        min-idle: 1
        # 最大连接数
        max-active: 8
      # 关闭超时时间
      shutdown-timeout: 100ms
    timeout: 10000ms

server:
  port: 8561

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /
  endpoint:
    health:
      show-details: always
