server:
  port: 8762
spring:
  application:
    name: client
#  zipkin:
#    base-url: http://localhost:9411
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 19941128ya
    virtual-host: test
    listener:
      type: simple
      simple:
        # 采取手动应答
        acknowledge-mode: manual
        # 限制每次处理的数据个数
        prefetch: 1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1